# This workflow will get latest tag and bump the version.
# The version defaults to #minor unless #major or #patch are found in any commit message.

name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Last tag
      run: |
        tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo $tag
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
