# This workflow will rebase legacy-projects branch on new pushes to master

name: Rebase branch legacy-projects

on:
  # Trigger the workflow on push pull request or manually
  push: 
    branches: [ master ]

  workflow_dispatch:

jobs:
  rebase:
    name: Checkout legacy-projects and rebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'legacy-projects'
          
      - name: Automatic Rebase
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          BASE_BRANCH: develop
        run: |
          echo git remote -v
          git remote -v

          echo git fetch origin $BASE_BRANCH
          git fetch origin $BASE_BRANCH

          echo Adding origin as $GITHUB_REPOSITORY
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          HEAD_BRANCH=$(git branch --show-current)

          echo git remote -v
          git remote -v

          echo git fetch origin $BASE_BRANCH
          git fetch origin $BASE_BRANCH
          
          echo git pull --rebase origin $HEAD_BRANCH
          git pull --rebase origin $HEAD_BRANCH

          echo Rebasing $BASE_BRANCH onto $HEAD_BRANCH
          echo git rebase origin/$BASE_BRANCH
          git rebase origin/$BASE_BRANCH

          echo git push --force-with-lease origin $HEAD_BRANCH
          git push --force-with-lease origin $HEAD_BRANCH
