# This workflow will trigger on pull-request to master or develop.
# It will run the Swift Package tests, output the code coverage and upload it to Codecov.

name: Rebase branch legacy-projects

on:
  # Trigger the workflow on push pull request or manually
  push: 
    branches: [ develop ]

  workflow_dispatch:

jobs:
  rebase:
    name: Checkout legacy-projects and rebase
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'legacy-projects'
          
      - name: Rebase
        run: |
          git rebase origin/develop
          git push --force
