# This workflow will rebase legacy-projects branch on new pushes to master

name: Rebase branch legacy-projects

on:
  # Trigger the workflow on push pull request or manually
  push: 
    branches: [ master ]

  workflow_dispatch:

jobs:
  rebase:
    name: Checkout legacy-projects and rebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'legacy-projects'
          
      - name: Automatic Rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: develop
        run: |
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git remote add fork https://x-access-token:$COMMITTER_TOKEN@github.com/$HEAD_REPO.git

          set -o xtrace

          HEAD_BRANCH=$(git branch --show-current)
          echo "Rebasing $HEAD_BRANCH on to $BASE_BRANCH"

          # make sure branches are up-to-date
          git fetch origin $BASE_BRANCH
          git fetch fork $HEAD_BRANCH

          # do the rebase
          git checkout -b $HEAD_BRANCH fork/$HEAD_BRANCH
          git rebase origin/$BASE_BRANCH

          # push back
          git push --force-with-lease fork $HEAD_BRANCH
