# This workflow will rebase legacy-projects branch on new pushes to master

name: Rebase branch legacy-projects

on:
  # Trigger the workflow on push pull request or manually
  push: 
    branches: [ master ]

  workflow_dispatch:

jobs:
  rebase:
    name: Checkout legacy-projects and rebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'legacy-projects'
          
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
